//! The dispatcher's tests (`tests/core-dispatcher.test.mjs`), ported under
//! their sentences, each held to the Node trace of the same test
//! ([`traces`]).

// The tests' own scaffolding: a failure in it is the test's.
#![allow(clippy::unwrap_used, clippy::expect_used)]

mod adapters_failing_at_once;
mod agent_gone;
mod assigning;
mod cancelled_task;
mod carriers;
mod chief_not_up;
mod chiefs;
mod closing;
mod deleted_sessions;
mod deliveries;
mod exit_unsettled;
mod fixtures;
mod follow_ups;
mod interrupts;
mod lanes;
mod launch_stops;
mod looks;
mod no_adapter;
mod not_ready;
mod out_of_quota;
mod participant_leaves;
mod quota;
mod receipts;
mod restart;
mod review;
mod separate_callbacks;
mod session_windows;
mod sessions;
mod several_roles;
mod stops;
mod switched_conversation;
mod switching;
mod switching_deleted;
mod switching_handoffs;
mod switching_refused;
mod tasks;
mod the_dispatcher;
mod throws_early;
mod trace_untold;
mod traces;
mod turns_at_seams;
mod undeliverable;
mod unreadable_agents;
mod unsent;
mod window_closes;
mod window_takes_long;
mod window_traces;
mod windows;
mod withdrawn;
mod work_in_flight;
mod work_in_flight_launches;
mod work_in_flight_pastes;
