import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { chmod, mkdir, mkdtemp, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'
import { codexAuthPath, loadCodexAuth } from '../../hosts/lib/codex-auth.js'
import {
  buildImageRequestBody,
  decodeChatGptAccountId,
  extractImageFromEvents,
  imageFileToDataUrl,
  saveImagePng,
} from '../../hosts/lib/image.js'
import { spawnWithInput } from '../../hosts/lib/runners.js'
import { saveSession, workspaceKey } from '../../hosts/lib/state.js'
import {
  collectHandoff,
  parseTranscriptJsonl,
  serializeClaudeTranscript,
} from '../../hosts/lib/transcript.js'

// The payload CLI these tests used to drive is gone: a mode installs the
// generated skill and nothing else, so there is one CLI left — the manager's.
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const ENGINE = path.join(ROOT, 'hosts', 'lib')
const CF = path.join(ROOT, 'bin', 'cf.mjs')

async function withTempDir(fn) {
  const dir = await mkdtemp(path.join(os.tmpdir(), 'cf-cc-test-'))
  // Point the shared home at the temp dir for IN-PROCESS lib calls too, not just the
  // subprocess helpers that pass it explicitly. Without this, a direct saveSession()/
  // loadSession() in a test writes run artifacts into the developer's real ~/.consensflow.
  const oldHome = process.env.CONSENSFLOW_HOME
  process.env.CONSENSFLOW_HOME = path.join(dir, 'home')
  try {
    return await fn(dir)
  } finally {
    if (oldHome === undefined) delete process.env.CONSENSFLOW_HOME
    else process.env.CONSENSFLOW_HOME = oldHome
    await rm(dir, { recursive: true, force: true })
  }
}

// --- Transcript serialization (the CC handoff) ----------------------------

function userEntry(content, extra = {}) {
  return { type: 'user', message: { role: 'user', content }, isSidechain: false, ...extra }
}

function assistantEntry(content, extra = {}) {
  return {
    type: 'assistant',
    message: { role: 'assistant', content },
    isSidechain: false,
    ...extra,
  }
}

test('serializeClaudeTranscript keeps chronological order with role labels and tool calls', () => {
  const entries = [
    userEntry('first question'),
    assistantEntry([
      { type: 'thinking', thinking: 'private reasoning' },
      { type: 'text', text: 'First reply' },
    ]),
    userEntry('second question'),
    assistantEntry([
      { type: 'text', text: 'Second reply' },
      { type: 'tool_use', id: 't1', name: 'Read', input: { file_path: 'a.ts' } },
    ]),
  ]
  const text = serializeClaudeTranscript(entries, { maxBytes: 10000 })
  assert.match(text, /User:\nfirst question/)
  assert.match(text, /Lead:\nFirst reply/)
  assert.match(text, /→ Read\(/)
  assert.ok(text.indexOf('first question') < text.indexOf('second question'), 'chronological order')
  assert.doesNotMatch(text, /private reasoning/)
})

test('serializeClaudeTranscript labels tool results via the tool_use map and skips noise', () => {
  const entries = [
    assistantEntry([{ type: 'tool_use', id: 't1', name: 'Bash', input: { command: 'ls' } }]),
    userEntry([{ type: 'tool_result', tool_use_id: 't1', content: 'file-a\nfile-b' }]),
    {
      type: 'user',
      message: { role: 'user', content: '<command-name>/clear</command-name>' },
      isSidechain: false,
    },
    {
      type: 'user',
      message: {
        role: 'user',
        content:
          'Caveat: The messages below were generated by the user while running local commands.',
      },
      isSidechain: false,
    },
    {
      type: 'user',
      message: { role: 'user', content: 'meta note' },
      isMeta: true,
      isSidechain: false,
    },
    { type: 'user', message: { role: 'user', content: 'from a subagent' }, isSidechain: true },
    { type: 'file-history-snapshot', snapshot: {} },
    { type: 'system', subtype: 'local_command', content: 'ran /clear' },
    userEntry('real question'),
  ]
  const text = serializeClaudeTranscript(entries)
  assert.match(text, /Tool result Bash:\nfile-a/)
  assert.match(text, /User:\nreal question/)
  assert.doesNotMatch(text, /command-name/)
  assert.doesNotMatch(text, /Caveat: The messages below/)
  assert.doesNotMatch(text, /meta note/)
  assert.doesNotMatch(text, /from a subagent/)
  assert.doesNotMatch(text, /ran \/clear/)
})

test('serializeClaudeTranscript keeps ConsensFlow run results near-whole (cross-pollination)', () => {
  const reply = 'A'.repeat(5000)
  const entries = [
    assistantEntry([
      {
        type: 'tool_use',
        id: 't1',
        name: 'Bash',
        input: {
          command:
            'node "/plug/bin/cf.mjs" run @iris --prompt-file "/ws/.consensflow/pending-prompt.md"',
        },
      },
    ]),
    userEntry([{ type: 'tool_result', tool_use_id: 't1', content: reply }]),
    assistantEntry([{ type: 'tool_use', id: 't2', name: 'Read', input: { file_path: 'a.ts' } }]),
    userEntry([{ type: 'tool_result', tool_use_id: 't2', content: reply }]),
  ]
  const text = serializeClaudeTranscript(entries)
  // The consultation survives beyond the generic cap; ordinary tool results stay tightly truncated.
  assert.match(text, /Tool result consensflow run \(@iris\):/)
  assert.ok(text.includes(reply), 'cf run reply kept near-whole')
  assert.match(text, /Tool result Read:\nA{1500}…\[truncated\]/)
})

test('serializeClaudeTranscript honors compaction and summary entries', () => {
  const entries = [
    { type: 'summary', summary: 'session about cache design', leafUuid: 'x' },
    userEntry('compacted away question', {
      isCompactSummary: true,
      message: { role: 'user', content: 'the earlier stuff' },
    }),
    userEntry('kept question'),
  ]
  const text = serializeClaudeTranscript(entries)
  assert.match(text, /\[Session summary\]\nsession about cache design/)
  assert.match(text, /\[Earlier conversation summary\]\nthe earlier stuff/)
  assert.match(text, /User:\nkept question/)
})

test('serializeClaudeTranscript caps bytes keeping the tail, and handles empty input', () => {
  const long = Array.from({ length: 50 }, () => userEntry('x'.repeat(500)))
  const text = serializeClaudeTranscript(long, { maxBytes: 2000 })
  assert.ok(Buffer.byteLength(text, 'utf8') <= 2000)
  assert.match(text, /\[earlier handoff truncated\]/)
  assert.equal(serializeClaudeTranscript([]), '')
  assert.equal(serializeClaudeTranscript(null), '')
})

test('serializeClaudeTranscript honors the CONSENSFLOW_HANDOFF_MAX_BYTES env budget when no maxBytes is passed', () => {
  // ~25 KB of entries: under the 48 KB default (no truncation), so the marker proves the env took effect.
  const long = Array.from({ length: 50 }, () => userEntry('x'.repeat(500)))
  const prev = process.env.CONSENSFLOW_HANDOFF_MAX_BYTES
  try {
    process.env.CONSENSFLOW_HANDOFF_MAX_BYTES = '2000'
    const text = serializeClaudeTranscript(long) // no options -> env budget applies
    assert.ok(Buffer.byteLength(text, 'utf8') <= 2000)
    assert.match(text, /\[earlier handoff truncated\]/)
  } finally {
    if (prev === undefined) delete process.env.CONSENSFLOW_HANDOFF_MAX_BYTES
    else process.env.CONSENSFLOW_HANDOFF_MAX_BYTES = prev
  }
})

test('parseTranscriptJsonl tolerates garbage lines and collectHandoff degrades to empty', async () => {
  const entries = parseTranscriptJsonl(
    `{"type":"user","message":{"role":"user","content":"hi"}}\nnot json\n\n{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"yo"}]}}`,
  )
  assert.equal(entries.length, 2)
  await withTempDir(async (dir) => {
    // No session stash at all -> empty handoff, no throw.
    assert.equal(await collectHandoff(dir), '')
    // Stash pointing at a missing transcript -> still empty, no throw.
    await saveSession(dir, { transcriptPath: path.join(dir, 'missing.jsonl') })
    assert.equal(await collectHandoff(dir), '')
    // Real transcript -> serialized handoff.
    const transcriptPath = path.join(dir, 't.jsonl')
    await writeFile(
      transcriptPath,
      `${JSON.stringify({ type: 'user', message: { role: 'user', content: "let's design the cache" }, isSidechain: false })}\n`,
      'utf8',
    )
    await saveSession(dir, { transcriptPath })
    assert.match(await collectHandoff(dir), /User:\nlet's design the cache/)
  })
})

// A ConsensFlow update ships a new catalog while the roster keeps its old snapshot. The
// session-start note is where the lead first sees that, so it must say so and name the fix.
// --- CLI end-to-end with fake engine binaries -------------------------------
// Per project policy, live harness CLIs are never invoked from tests. Each engine gets a PATH shim
// that dumps its argv/env/stdin to a file and prints engine-shaped output, so the full spawn →
// packet → parse → artifact path is exercised for all four engines.

const SHIM_BODIES = {
  claude: `console.log(JSON.stringify({ type: "system", subtype: "init" }));
console.log(JSON.stringify({ type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "CLAUDE OK" }] } }));
console.log(JSON.stringify({ type: "result", subtype: "success", is_error: false, result: "CLAUDE OK" }));`,
  codex: `console.log(JSON.stringify({ type: "thread.started", thread_id: "t" }));\nconsole.log(JSON.stringify({ type: "item.completed", item: { type: "agent_message", text: "CODEX OK" } }));`,
  pi: `console.log(JSON.stringify({ type: "agent_end", messages: [{ role: "assistant", content: [{ type: "text", text: "PI OK" }] }] }));`,
  opencode: `console.log(JSON.stringify({ type: "text", part: { type: "text", text: "OPENCODE OK" } }));`,
}

async function makeFakeEngines(dir) {
  const bin = path.join(dir, 'fakebin')
  const out = path.join(dir, 'engine-out')
  await mkdir(bin, { recursive: true })
  await mkdir(out, { recursive: true })
  for (const [name, body] of Object.entries(SHIM_BODIES)) {
    const source = [
      '#!/usr/bin/env node',
      'const fs = require("node:fs");',
      'const path = require("node:path");',
      'let stdin = "";',
      'try { stdin = fs.readFileSync(0, "utf8"); } catch {}',
      'let packetFromFile = null;',
      'const fileIdx = process.argv.indexOf("--file");',
      'if (fileIdx >= 0) { try { packetFromFile = fs.readFileSync(process.argv[fileIdx + 1], "utf8"); } catch {} }',
      'const dump = {',
      `  name: ${JSON.stringify(name)},`,
      '  argv: process.argv.slice(2),',
      '  stdin,',
      '  packetFromFile,',
      '  env: {',
      '    CONSENSFLOW_CHILD: process.env.CONSENSFLOW_CHILD ?? null,',
      '    OPENCODE_PERMISSION: process.env.OPENCODE_PERMISSION ?? null,',
      '    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY ?? null,',
      '    OPENAI_API_KEY: process.env.OPENAI_API_KEY ?? null,',
      '    CMUX_SOCKET_CAPABILITY: process.env.CMUX_SOCKET_CAPABILITY ?? null,',
      '    CMUX_CLAUDE_HOOK_CMUX_BIN: process.env.CMUX_CLAUDE_HOOK_CMUX_BIN ?? null,',
      '  },',
      '};',
      `fs.writeFileSync(path.join(process.env.FAKE_ENGINE_OUT, ${JSON.stringify(name)} + ".json"), JSON.stringify(dump, null, 2));`,
      body,
    ].join('\n')
    const shimPath = path.join(bin, name)
    await writeFile(shimPath, source, 'utf8')
    await chmod(shimPath, 0o755)
  }
  return { bin, out }
}

async function runCf(args, { ws, dir, fake }, extraEnv = {}) {
  return await spawnWithInput(process.execPath, [CF, ...args], {
    cwd: ws,
    timeoutMs: 30000,
    env: {
      CONSENSFLOW_HOME: path.join(dir, 'home'),
      PATH: `${fake.bin}${path.delimiter}${process.env.PATH}`,
      FAKE_ENGINE_OUT: fake.out,
      // Billing guard probe: these must NOT reach claude/codex children.
      ANTHROPIC_API_KEY: 'leak-test',
      OPENAI_API_KEY: 'leak-test',
      // cmux control-socket guard probe: the bearer token must NOT reach any child.
      CMUX_SOCKET_CAPABILITY: 'leak-test',
      CMUX_CLAUDE_HOOK_CMUX_BIN: 'leak-test',
      ...extraEnv,
    },
  })
}

async function latestPacket(ws, dir) {
  const current = JSON.parse(
    await readFile(path.join(dir, 'home', 'workspaces', workspaceKey(ws), 'current.json'), 'utf8'),
  )
  return {
    current,
    packet: await readFile(path.join(current.latestRunDir, 'packet.md'), 'utf8'),
    result: JSON.parse(await readFile(path.join(current.latestRunDir, 'result.json'), 'utf8')),
  }
}

test('e2e: all four engines run, parse, and persist artifacts through the real spawn path', async () => {
  await withTempDir(async (dir) => {
    const ws = path.join(dir, 'ws')
    await mkdir(ws, { recursive: true })
    const fake = await makeFakeEngines(dir)
    const ctx = { ws, dir, fake }
    for (const preset of ['zeus', 'gaia', 'kronos', 'mani']) {
      const add = await runCf(['agent', 'add', preset], ctx)
      assert.equal(add.exitCode, 0, add.stderr)
    }

    const cases = [
      { ref: '@zeus', engine: 'claude', expect: 'CLAUDE OK' },
      { ref: '@gaia', engine: 'codex', expect: 'CODEX OK' },
      { ref: '@kronos', engine: 'pi', expect: 'PI OK' },
      { ref: '@mani', engine: 'opencode', expect: 'OPENCODE OK' },
    ]
    for (const { ref, engine, expect } of cases) {
      const run = await runCf(['run', ref, 'ping', 'from', 'the', 'test'], ctx)
      assert.equal(run.exitCode, 0, `${ref}: ${run.stderr}`)
      // Attributed either way: `# @name` with the answer under it, or `— @name`
      // alone when the answer already streamed and repeating it would be noise.
      assert.match(run.stdout, new RegExp(`[#—] ${ref}`), `${ref}: attributed`)
      assert.ok(run.stdout.includes(expect), `${ref}: parsed engine output`)
      // Clean output: a successful read-only run shows just the answer — no run metadata, no
      // consent boilerplate. (The `Handoff: empty` warning IS expected here: this test never
      // stashes a transcript; the handoff e2e below covers when that line appears.)
      assert.doesNotMatch(run.stdout, /Run:|Exit:|Artifacts:|approval/, `${ref}: no metadata noise`)

      const { packet, result } = await latestPacket(ws, dir)
      assert.match(packet, /# ConsensFlow Packet/)
      assert.match(packet, /You can read and modify this workspace/)
      assert.match(packet, /ping from the test/)
      assert.equal(result.output, expect)
      assert.equal(result.exitCode, 0)

      const dump = JSON.parse(await readFile(path.join(fake.out, `${engine}.json`), 'utf8'))
      assert.equal(
        dump.env.CONSENSFLOW_CHILD,
        '1',
        `${engine}: child marker reaches the subprocess`,
      )
      assert.equal(dump.env.CMUX_SOCKET_CAPABILITY, null, `${engine}: cmux socket token stripped`)
      assert.equal(
        dump.env.CMUX_CLAUDE_HOOK_CMUX_BIN,
        null,
        `${engine}: cmux hook binary path stripped`,
      )
      const packetSeen = engine === 'opencode' ? dump.packetFromFile : dump.stdin
      assert.ok(
        String(packetSeen ?? '').includes('# ConsensFlow Packet'),
        `${engine}: packet delivered`,
      )
    }

    // The relocation contract: a run never creates anything inside the project workspace.
    assert.ok(
      !(await readdir(ws)).some((entry) => entry.startsWith('.consensflow')),
      'no .consensflow* dir in the workspace',
    )

    // Engine-specific guards observed from inside the children.
    const claude = JSON.parse(await readFile(path.join(fake.out, 'claude.json'), 'utf8'))
    assert.ok(
      !claude.argv.includes('--bare'),
      'claude child must NOT run --bare: it forbids OAuth/keychain auth while ANTHROPIC_API_KEY is stripped (1.5.1 regression guard); recursion is covered by CONSENSFLOW_CHILD',
    )
    assert.equal(claude.argv.includes('--disallowedTools'), false, 'no claude deny list')
    assert.equal(claude.argv[claude.argv.indexOf('--model') + 1], 'claude-opus-5')
    assert.equal(claude.argv[claude.argv.indexOf('--effort') + 1], 'max')
    assert.equal(claude.env.ANTHROPIC_API_KEY, null, 'billing guard strips ANTHROPIC_API_KEY')
    const codex = JSON.parse(await readFile(path.join(fake.out, 'codex.json'), 'utf8'))
    assert.equal(codex.argv.includes('--sandbox'), false, 'no sandbox policy is selected')
    assert.ok(
      codex.argv.includes('--dangerously-bypass-approvals-and-sandbox'),
      'codex runs unsandboxed',
    )
    assert.equal(codex.env.OPENAI_API_KEY, null, 'billing guard strips OPENAI_API_KEY')
    const piDump = JSON.parse(await readFile(path.join(fake.out, 'pi.json'), 'utf8'))
    assert.ok(piDump.argv.includes('--no-extensions'), 'pi child runs without extensions')
    assert.equal(piDump.argv[piDump.argv.indexOf('--thinking') + 1], 'xhigh')
    const opencode = JSON.parse(await readFile(path.join(fake.out, 'opencode.json'), 'utf8'))
    assert.equal(opencode.env.OPENCODE_PERMISSION, null, 'no opencode permission overlay')
  })
})

test('e2e: streaming is the default (thinking always visible); --json is the only quiet mode [STRM-17]', async () => {
  await withTempDir(async (dir) => {
    const ws = path.join(dir, 'ws')
    await mkdir(ws, { recursive: true })
    const bin = path.join(dir, 'fakebin')
    await mkdir(bin, { recursive: true })
    // A fake opencode that emits a real-shaped tool_use + text part, then exits cleanly.
    const shim = [
      '#!/usr/bin/env node',
      `console.log(JSON.stringify({ type: "tool_use", part: { type: "tool", tool: "read", state: { input: { path: "f.txt" }, output: "body" } } }));`,
      `console.log(JSON.stringify({ type: "text", part: { text: "the streamed answer" } }));`,
    ].join('\n')
    const shimPath = path.join(bin, 'opencode')
    await writeFile(shimPath, shim, 'utf8')
    await chmod(shimPath, 0o755)
    // A fake pi that reports its final answer only in agent_end. The stream adapter intentionally
    // skips agent_end to avoid duplicate message_end text, so the CLI must print the parsed final
    // result after --stream when no answer text streamed.
    const piShim = [
      '#!/usr/bin/env node',
      `console.log(JSON.stringify({ type: "agent_end", messages: [{ role: "assistant", content: [{ type: "text", text: "PI FALLBACK FINAL" }] }] }));`,
    ].join('\n')
    const piShimPath = path.join(bin, 'pi')
    await writeFile(piShimPath, piShim, 'utf8')
    await chmod(piShimPath, 0o755)
    const ctx = { ws, dir, fake: { bin, out: dir } }
    await runCf(['agent', 'add', 'mani'], ctx)

    // Streaming needs no flag. The parsed final reply is still printed after the child exits,
    // so a foreground run always ends with a durable, attributed answer section.
    const streamed = await runCf(
      // One quoted task, the way the skill teaches it — so a `--stat` inside the
      // prompt is text, not an option the manager's strict parser must guess at.
      ['run', '@mani', 'go check git diff --stat'],
      ctx,
    )
    assert.match(streamed.stdout, /→ .*read/, 'the tool call is streamed live')
    assert.match(streamed.stdout, /the streamed answer/, 'the text is streamed live')
    assert.match(
      streamed.stdout,
      /[#—] @mani/,
      'the final answer section is printed after the stream',
    )
    assert.match(
      (await latestPacket(ws, dir)).packet,
      /go check git diff --stat/,
      'flag-like text inside the task survives into the packet',
    )

    // Streaming is the default — thinking/tools are ALWAYS visible. A run without --stream still
    // streams; only --json suppresses the live trail (machine-readable output).
    const plain = await runCf(['run', '@mani', 'go'], ctx)
    assert.match(plain.stdout, /the streamed answer/, 'the answer is present')
    assert.match(
      plain.stdout,
      /→ .*read/,
      'event lines stream by default — no --stream flag needed',
    )
    const quiet = await runCf(['run', '@mani', 'go', '--json'], ctx)
    assert.doesNotMatch(quiet.stdout, /→ .*read|← .*read/, '--json is the only quiet mode')

    assert.equal(
      // The manager validates names rather than slugifying them, so it is spelled
      // here exactly as `@pionly` refers to it below.
      (await runCf(['agent', 'add', 'pionly', '--harness', 'pi', '--model', 'fake'], ctx)).exitCode,
      0,
    )
    const fallback = await runCf(['run', '@pionly', 'go'], ctx)
    assert.match(
      fallback.stdout,
      /PI FALLBACK FINAL/,
      'the final output is printed even when no text event streamed',
    )
  })
})

test('e2e: runAgent writes a transcript.md backstop (event trail) and sets transcriptPath [STRM-19]', async () => {
  await withTempDir(async (dir) => {
    const ws = path.join(dir, 'ws')
    await mkdir(ws, { recursive: true })
    const bin = path.join(dir, 'fakebin')
    await mkdir(bin, { recursive: true })
    const shim = [
      '#!/usr/bin/env node',
      `console.log(JSON.stringify({ type: "tool_use", part: { type: "tool", tool: "read", state: { input: { path: "f.txt" }, output: "file body" } } }));`,
      `console.log(JSON.stringify({ type: "text", part: { text: "the backstopped answer" } }));`,
    ].join('\n')
    const shimPath = path.join(bin, 'opencode')
    await writeFile(shimPath, shim, 'utf8')
    await chmod(shimPath, 0o755)
    const ctx = { ws, dir, fake: { bin, out: dir } }
    await runCf(['agent', 'add', 'mani'], ctx)

    const run = await runCf(['run', '@mani', 'go', '--json'], ctx)
    const result = JSON.parse(run.stdout)
    assert.ok(result.transcriptPath, 'result.json carries transcriptPath')
    const transcript = await readFile(result.transcriptPath, 'utf8')
    assert.ok(transcript.trim().length > 0, 'transcript.md is non-empty')
    assert.match(transcript, /read/, 'transcript includes the tool call')
    assert.match(transcript, /the backstopped answer/, 'transcript includes the answer, in order')
  })
})

test('e2e: a run has full permissions, and there is still no knob to turn [STRM-25]', async () => {
  await withTempDir(async (dir) => {
    const ws = path.join(dir, 'ws')
    await mkdir(ws, { recursive: true })
    const fake = await makeFakeEngines(dir)
    const ctx = { ws, dir, fake }
    await runCf(['agent', 'add', 'zeus'], ctx) // claude-code

    // Every run is full-permission: no allowlist, no deny list, no prompts.
    await runCf(['run', '@zeus', 'go'], ctx)
    let claude = JSON.parse(await readFile(path.join(fake.out, 'claude.json'), 'utf8'))
    assert.ok(
      claude.argv.includes('--dangerously-skip-permissions'),
      'default run bypasses prompts',
    )
    assert.equal(claude.argv.includes('--allowedTools'), false, 'no allowlist fences the tools')
    assert.equal(claude.argv.includes('--disallowedTools'), false, 'no deny list')

    // There is still no permission knob: asking for one changes nothing, because
    // every run already has everything.
    await runCf(['run', '@zeus', 'go', '--tools', 'full-auto'], ctx)
    claude = JSON.parse(await readFile(path.join(fake.out, 'claude.json'), 'utf8'))
    assert.ok(
      claude.argv.includes('--dangerously-skip-permissions'),
      'the flag is the default, not an escalation',
    )
  })
})

test('e2e: nested runs are refused and unknown agents error cleanly', async () => {
  await withTempDir(async (dir) => {
    const ws = path.join(dir, 'ws')
    await mkdir(ws, { recursive: true })
    const fake = await makeFakeEngines(dir)
    const ctx = { ws, dir, fake }
    assert.equal((await runCf(['agent', 'add', 'zeus'], ctx)).exitCode, 0)

    const unknown = await runCf(['run', '@ghost', 'hi'], ctx)
    assert.equal(unknown.exitCode, 1)
    assert.match(unknown.stderr, /no agent named "ghost"/)
    assert.match(unknown.stderr, /zeus/, 'it names who you do have')

    const nested = await spawnWithInput(process.execPath, [CF, 'run', '@zeus', 'hi'], {
      cwd: ws,
      timeoutMs: 15000,
      env: { CONSENSFLOW_HOME: path.join(dir, 'home'), CONSENSFLOW_CHILD: '1' },
    })
    assert.equal(nested.exitCode, 1)
    assert.match(nested.stderr, /already an agent run — an agent does not spawn agents/)
  })
})

// --- Image agents (Codex backend) -------------------------------------

function fakeJwt(claims) {
  const payload = Buffer.from(JSON.stringify(claims)).toString('base64url')
  return `header.${payload}.signature`
}

test('image helpers: JWT account id, request body, SSE extraction, PNG save', async () => {
  // decodeChatGptAccountId pulls the claim out of a ChatGPT OAuth JWT.
  assert.equal(
    decodeChatGptAccountId(
      fakeJwt({ 'https://api.openai.com/auth': { chatgpt_account_id: 'acc_42' } }),
    ),
    'acc_42',
  )
  assert.throws(() => decodeChatGptAccountId('not-a-jwt'), /JWT/)

  // buildImageRequestBody triggers exactly one image_generation call with the prompt.
  const body = buildImageRequestBody('a red cat', 'gpt-5.5')
  assert.equal(body.model, 'gpt-5.5')
  assert.equal(body.tools[0].type, 'image_generation')
  assert.equal(body.input[0].content[0].text, 'a red cat')
  // Without references the content is text-only (no input_image parts) — regression guard.
  assert.equal(body.input[0].content.length, 1)
  assert.equal(
    body.input[0].content.some((part) => part.type === 'input_image'),
    false,
  )

  // With reference images, each becomes an input_image part (image_url is a plain string), after the text.
  const refs = ['data:image/png;base64,AAA', 'data:image/jpeg;base64,BBB']
  const refBody = buildImageRequestBody('blend these', 'gpt-5.5', refs)
  assert.equal(refBody.input[0].content[0].type, 'input_text')
  const imageParts = refBody.input[0].content.filter((part) => part.type === 'input_image')
  assert.equal(imageParts.length, 2)
  assert.deepEqual(
    imageParts.map((part) => part.image_url),
    refs,
  )
  assert.match(refBody.instructions, /reference image/i)
  // Non-string / empty entries are dropped so a stray value can't corrupt the request.
  assert.equal(buildImageRequestBody('p', 'gpt-5.5', ['', null, 5]).input[0].content.length, 1)

  // extractImageFromEvents finds the base64 image + metadata across SSE events.
  const img = extractImageFromEvents([
    { type: 'response.created', response: { id: 'r1' } },
    {
      type: 'response.output_item.done',
      item: {
        type: 'image_generation_call',
        id: 'i1',
        status: 'completed',
        result: 'QkFTRTY0',
        revised_prompt: 'a bright red cat',
      },
    },
    { type: 'response.completed', response: { id: 'r1' } },
  ])
  assert.equal(img.base64, 'QkFTRTY0')
  assert.equal(img.revisedPrompt, 'a bright red cat')
  assert.equal(img.responseId, 'r1')
  assert.throws(() => extractImageFromEvents([{ type: 'error', message: 'boom' }]), /boom/)
  assert.throws(
    () =>
      extractImageFromEvents([
        { type: 'response.failed', response: { error: { message: 'content blocked' } } },
      ]),
    /content blocked/,
  )
  // A text-only / empty stream yields no image rather than a bogus base64.
  assert.equal(
    extractImageFromEvents([{ type: 'response.output_text.delta', delta: 'hi' }]).base64,
    undefined,
  )
  assert.equal(extractImageFromEvents([]).base64, undefined)

  // saveImagePng decodes base64 and writes the file.
  await withTempDir(async (dir) => {
    const saved = await saveImagePng(
      Buffer.from('PNGDATA').toString('base64'),
      path.join(dir, 'runs', 'img1'),
      'image.png',
    )
    assert.equal((await readFile(saved)).toString(), 'PNGDATA')
  })
})

test('reference images: imageFileToDataUrl encodes by extension; rejects unknown/missing', async () => {
  await withTempDir(async (dir) => {
    const pngPath = path.join(dir, 'ref.png')
    await writeFile(pngPath, Buffer.from('PNGBYTES'))
    const url = await imageFileToDataUrl(pngPath)
    assert.equal(url, `data:image/png;base64,${Buffer.from('PNGBYTES').toString('base64')}`)

    // Extension drives the mime type (case-insensitive).
    const jpgPath = path.join(dir, 'ref.JPG')
    await writeFile(jpgPath, Buffer.from('JPGBYTES'))
    assert.match(await imageFileToDataUrl(jpgPath), /^data:image\/jpeg;base64,/)

    // Unsupported extension and missing file both throw clearly.
    await writeFile(path.join(dir, 'ref.txt'), 'nope')
    await assert.rejects(
      () => imageFileToDataUrl(path.join(dir, 'ref.txt')),
      /Unsupported reference image/,
    )
    await assert.rejects(
      () => imageFileToDataUrl(path.join(dir, 'missing.png')),
      /ENOENT|no such file/,
    )
  })
})

// `parseRunOptions` was the payload CLI's hand-rolled argument parser, and it
// went with the payload. The manager parses with node's own `parseArgs`
// (`image: { type: 'string', multiple: true }`, bin/cf.mjs), which is where
// `--image x` / `--image=x` / repeats are handled now.

test('loadCodexAuth reads the Codex CLI login (account_id field, JWT fallback, clear errors)', async () => {
  await withTempDir(async (dir) => {
    const oldCodexHome = process.env.CODEX_HOME
    process.env.CODEX_HOME = path.join(dir, 'codex-home')
    try {
      // No auth file at all → fix-it error naming the path.
      assert.match(codexAuthPath(), /codex-home/)
      await assert.rejects(loadCodexAuth(), /codex login/)

      // access_token + explicit account_id → both returned verbatim.
      await mkdir(process.env.CODEX_HOME, { recursive: true })
      const token = fakeJwt({ 'https://api.openai.com/auth': { chatgpt_account_id: 'acc_jwt' } })
      await writeFile(
        path.join(process.env.CODEX_HOME, 'auth.json'),
        JSON.stringify({ tokens: { access_token: token, account_id: 'acc_field' } }),
        'utf8',
      )
      assert.deepEqual(await loadCodexAuth(), { token, accountId: 'acc_field' })

      // Missing account_id field → decoded from the JWT claim.
      await writeFile(
        path.join(process.env.CODEX_HOME, 'auth.json'),
        JSON.stringify({ tokens: { access_token: token } }),
        'utf8',
      )
      assert.deepEqual(await loadCodexAuth(), { token, accountId: 'acc_jwt' })

      // Claim-less access token falls back to the id_token's claim.
      const bare = fakeJwt({ sub: 'x' })
      const idToken = fakeJwt({
        'https://api.openai.com/auth': { chatgpt_account_id: 'acc_id_token' },
      })
      await writeFile(
        path.join(process.env.CODEX_HOME, 'auth.json'),
        JSON.stringify({ tokens: { access_token: bare, id_token: idToken } }),
        'utf8',
      )
      assert.equal((await loadCodexAuth()).accountId, 'acc_id_token')

      // API-key-only auth (no ChatGPT tokens) → clear error.
      await writeFile(
        path.join(process.env.CODEX_HOME, 'auth.json'),
        JSON.stringify({ OPENAI_API_KEY: 'sk-test' }),
        'utf8',
      )
      await assert.rejects(loadCodexAuth(), /no ChatGPT access token/)
    } finally {
      if (oldCodexHome === undefined) delete process.env.CODEX_HOME
      else process.env.CODEX_HOME = oldCodexHome
    }
  })
})

test('e2e: @pygmalion without a Codex login errors cleanly before any network call', async () => {
  await withTempDir(async (dir) => {
    const ws = path.join(dir, 'ws')
    await mkdir(ws, { recursive: true })
    const fake = await makeFakeEngines(dir)
    const ctx = { ws, dir, fake }
    assert.equal((await runCf(['agent', 'add', 'pygmalion'], ctx)).exitCode, 0)
    const run = await runCf(['run', '@pygmalion', 'a', 'minimalist', 'logo'], ctx, {
      CODEX_HOME: path.join(dir, 'empty-codex-home'),
    })
    assert.equal(run.exitCode, 1)
    assert.match(run.stderr, /No Codex CLI login found/)
    assert.match(run.stderr, /codex login/)
  })
})

// --- Plugin packaging: consent gate, hooks wiring, import boundaries --------

test('the consent gate and name-neutrality stay locked into the generated skill', async () => {
  // There is one skill now, and it is generated — so the gate has to live in
  // the generator, not in a hand-written copy per host. The payload skills
  // that used to carry their own copy are gone.
  const { generateSkill } = await import('../../src/skill.js')
  const skill = generateSkill([
    { name: 'zeus', harness: 'claude', model: 'claude-opus-5', effort: 'max' },
  ])
  assert.match(skill, /Advice is free; acting is gated/)
  assert.match(skill, /without the user's explicit approval/)
  assert.match(skill, /You do not need permission to consult/)

  // No host payload ships any more, so no second copy of the gate can drift.
  assert.equal(existsSync(path.join(ROOT, 'hosts', 'claude')), false, 'no claude payload')
  assert.equal(existsSync(path.join(ROOT, 'hosts', 'pi')), false, 'no pi payload')

  // The personal name must not appear in anything that ships.
  for (const base of [ENGINE, path.join(ROOT, 'bin'), path.join(ROOT, 'src')]) {
    for (const file of await readdir(base, { recursive: true })) {
      const full = path.join(base, file)
      const content = await readFile(full, 'utf8').catch(() => '')
      assert.doesNotMatch(content, /Gabriel/, `${base}/${file}`)
    }
  }
})
