/**
 * Generates the consensflow SKILL.md from the roster.
 *
 * The prose is the product: this template is the hand-written v0 skill that
 * was live-proven on claude and codex (2026-08-19) before any of this code
 * existed. Only the roster table and the description's name list vary.
 *
 * The `env -u …_API_KEY` prefixes are deliberate: they keep subscription
 * logins from silently switching to API-key billing (v1's dropEnv, carried
 * as prose). The danger flags appear only on rows the user explicitly stored
 * as full-auto — the table is copy-paste commands a lead will run verbatim.
 */

const q = '"<question>"'

const COMMANDS = {
  claude: (p) =>
    [
      'env -u ANTHROPIC_API_KEY claude -p',
      q,
      '--model',
      p.model,
      ...(p.effort ? ['--effort', p.effort] : []),
      ...(p.permission === 'full-auto' ? ['--dangerously-skip-permissions'] : []),
    ].join(' '),
  codex: (p) =>
    [
      'env -u OPENAI_API_KEY codex exec --skip-git-repo-check -m',
      p.model,
      ...(p.effort ? ['-c', `model_reasoning_effort="${p.effort}"`] : []),
      ...(p.permission === 'full-auto' ? ['--dangerously-bypass-approvals-and-sandbox'] : []),
      q,
    ].join(' '),
  pi: (p) =>
    [
      'pi --no-session --model',
      p.model,
      ...(p.effort ? ['--thinking', p.effort] : []),
      ...(p.permission === 'full-auto' ? ['--dangerously-skip-permissions'] : []),
      '-p',
      q,
    ].join(' '),
  opencode: (p) =>
    ['opencode run --model', p.model, ...(p.effort ? ['--variant', p.effort] : []), q].join(' '),
}

function row(p) {
  const traits = [
    p.description,
    p.effort ? `${p.effort} effort` : null,
    p.permission === 'full-auto' ? 'FULL-AUTO' : null,
  ]
    .filter(Boolean)
    .join('; ')
  const label = traits.length > 0 ? `**${p.name}** — ${traits}` : `**${p.name}**`
  return `| ${label} | ${p.runtime} | \`${COMMANDS[p.runtime](p)}\` |`
}

export function generateSkill(participants) {
  const supported = participants.filter((p) => COMMANDS[p.runtime] !== undefined)
  if (supported.length === 0) {
    throw new Error('empty roster: add a participant before generating the skill')
  }
  const names = supported.map((p) => p.name).join(', ')

  return `---
name: consensflow
description: Consult one of the user's named AI participants — ${names} — each a real coding-agent CLI (claude, codex, pi, opencode) run one-shot in the current directory. Use whenever the user says "ask <name> …", "what does <name> think", "consult <name>", "get a second opinion from <name>", or names any participant — and also when you yourself want an independent second opinion on a risky or debatable decision.
---

# ConsensFlow participants

The user keeps a roster of named AI participants. Each participant is a real,
separately-installed coding-agent CLI with a fixed model and effort. Consulting
one means running its one-shot command below with your question as the final
argument. The participant runs in **your current working directory** — it can
read the project's files itself, so you do not need to paste file contents.

## How to consult

1. Pick the participant the user named (or choose one yourself when you want
   a second opinion).
2. Compose the question: one or two sentences of task context, then the
   concrete question. Name specific files with relative paths when relevant.
3. Run the participant's exact command from the table below, replacing only
   \`<question>\`. Run it from the project directory. Turns can take minutes at
   high effort — use a generous timeout (10+ minutes for max/ultra).
4. Report the answer to the user **verbatim or faithfully summarized, and
   attributed** ("hyperion says: …"). Never present a participant's answer as
   your own.

## Rules

- **One participant at a time.** Wait for one answer before asking another.
- **Advice is free; acting is gated.** Never apply a participant's suggested
  changes, or keep files it created, without the user's explicit approval —
  unless the user already authorized it in this conversation.
- **Do not retry a slow participant with a different one** unless the command
  itself failed. Slow usually means thinking.

## Roster

| Participant | Runs | Command (replace \`<question>\` only) |
|---|---|---|
${supported.map(row).join('\n')}

The \`env -u …_API_KEY\` prefixes are deliberate: they keep subscription
logins from silently switching to API-key billing. Keep them.

## Visible pane (optional)

By default, run the command inline and read its output. If the user asks to
*watch* the participant work and the cmux skills are installed, open a split in
the current cmux workspace with those skills and run the same command there —
this skill defines *what* to run; the cmux skills define pane control.

## Roster maintenance

The roster above is generated by ConsensFlow. To change it, the user runs
\`cf participant …\` or \`cf ui\` — never edit this file by hand; it will be
regenerated.
`
}
